#!/bin/bash

##############################################################################
# Claude Configuration Sync Script
# Author: Generated by Claude Code
# Date: 2025-11-11
# Purpose: Sync Claude configurations across platforms
##############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Paths
GLOBAL_CONFIG_DIR="/Users/YOUR_USERNAME/Claude-Code-Configs"
CLAUDE_CODE_DIR="/Users/YOUR_USERNAME/.claude"
CLAUDE_DESKTOP_CONFIG="/Users/YOUR_USERNAME/Library/Application Support/Claude"
BACKUP_DIR="$GLOBAL_CONFIG_DIR/backups/$(date +%Y%m%d-%H%M%S)"

##############################################################################
# Helper Functions
##############################################################################

print_header() {
    echo -e "${BLUE}============================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}============================================${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

##############################################################################
# Main Functions
##############################################################################

check_disk_space() {
    print_header "Checking Disk Space"

    AVAILABLE=$(df -h / | tail -1 | awk '{print $4}')
    PERCENT=$(df -h / | tail -1 | awk '{print $5}' | sed 's/%//')

    if [ "$PERCENT" -gt 95 ]; then
        print_warning "Disk is ${PERCENT}% full (${AVAILABLE} available)"
        print_warning "Consider cleaning up before full backup"
        return 1
    else
        print_success "Disk space OK: ${AVAILABLE} available"
        return 0
    fi
}

backup_configs() {
    print_header "Backing Up Configurations"

    mkdir -p "$BACKUP_DIR"

    # Backup essential config files only
    print_info "Backing up essential configs..."

    cp "$CLAUDE_CODE_DIR/settings.json" "$BACKUP_DIR/settings.json" 2>/dev/null || print_warning "settings.json not found"
    cp "$CLAUDE_CODE_DIR/settings.local.json" "$BACKUP_DIR/settings.local.json" 2>/dev/null || print_warning "settings.local.json not found"
    cp "$CLAUDE_DESKTOP_CONFIG/claude_desktop_config.json" "$BACKUP_DIR/claude_desktop_config.json" 2>/dev/null || print_warning "claude_desktop_config.json not found"

    # Backup agents, skills, workflows (smaller directories)
    cp -r "$CLAUDE_CODE_DIR/agents" "$BACKUP_DIR/agents" 2>/dev/null || print_warning "agents not found"
    cp -r "$CLAUDE_CODE_DIR/skills" "$BACKUP_DIR/skills" 2>/dev/null || print_warning "skills not found"
    cp -r "$CLAUDE_CODE_DIR/workflows" "$BACKUP_DIR/workflows" 2>/dev/null || print_warning "workflows not found"

    print_success "Backup created at: $BACKUP_DIR"
}

sync_to_global() {
    print_header "Syncing to Global Config"

    # Copy current configs to global
    cp "$CLAUDE_CODE_DIR/settings.json" "$GLOBAL_CONFIG_DIR/settings.json"
    cp "$CLAUDE_CODE_DIR/settings.local.json" "$GLOBAL_CONFIG_DIR/settings.local.json"
    cp "$CLAUDE_DESKTOP_CONFIG/claude_desktop_config.json" "$GLOBAL_CONFIG_DIR/claude_desktop_config.json"

    print_success "Synced to global config directory"
}

sync_from_global() {
    print_header "Syncing from Global Config"

    if [ -f "$GLOBAL_CONFIG_DIR/settings.json" ]; then
        cp "$GLOBAL_CONFIG_DIR/settings.json" "$CLAUDE_CODE_DIR/settings.json"
        print_success "Restored settings.json"
    fi

    if [ -f "$GLOBAL_CONFIG_DIR/settings.local.json" ]; then
        cp "$GLOBAL_CONFIG_DIR/settings.local.json" "$CLAUDE_CODE_DIR/settings.local.json"
        print_success "Restored settings.local.json"
    fi

    if [ -f "$GLOBAL_CONFIG_DIR/claude_desktop_config.json" ]; then
        cp "$GLOBAL_CONFIG_DIR/claude_desktop_config.json" "$CLAUDE_DESKTOP_CONFIG/claude_desktop_config.json"
        print_success "Restored claude_desktop_config.json"
    fi
}

validate_configs() {
    print_header "Validating Configurations"

    # Validate JSON syntax
    if command -v python3 &> /dev/null; then
        for file in "$CLAUDE_CODE_DIR/settings.json" \
                    "$CLAUDE_CODE_DIR/settings.local.json" \
                    "$CLAUDE_DESKTOP_CONFIG/claude_desktop_config.json"; do
            if [ -f "$file" ]; then
                if python3 -m json.tool "$file" > /dev/null 2>&1; then
                    print_success "$(basename "$file") is valid JSON"
                else
                    print_error "$(basename "$file") has JSON errors"
                fi
            fi
        done
    else
        print_warning "Python3 not found, skipping JSON validation"
    fi
}

show_status() {
    print_header "Configuration Status"

    echo ""
    echo "📁 Configuration Locations:"
    echo "   Global:        $GLOBAL_CONFIG_DIR"
    echo "   Claude Code:   $CLAUDE_CODE_DIR"
    echo "   Claude Desktop: $CLAUDE_DESKTOP_CONFIG"
    echo ""

    echo "📊 Component Counts:"
    [ -d "$CLAUDE_CODE_DIR/agents" ] && echo "   Agents:    $(ls -1 "$CLAUDE_CODE_DIR/agents" | wc -l | tr -d ' ')"
    [ -d "$CLAUDE_CODE_DIR/skills" ] && echo "   Skills:    $(ls -1 "$CLAUDE_CODE_DIR/skills" | wc -l | tr -d ' ')"
    [ -d "$CLAUDE_CODE_DIR/workflows" ] && echo "   Workflows: $(ls -1 "$CLAUDE_CODE_DIR/workflows" | wc -l | tr -d ' ')"
    [ -d "$CLAUDE_CODE_DIR/plugins" ] && echo "   Plugins:   $(ls -1 "$CLAUDE_CODE_DIR/plugins/marketplaces" 2>/dev/null | wc -l | tr -d ' ')"
    echo ""

    echo "🔧 MCP Servers:"
    if [ -f "$CLAUDE_DESKTOP_CONFIG/claude_desktop_config.json" ]; then
        MCP_COUNT=$(grep -o '"[^"]*":' "$CLAUDE_DESKTOP_CONFIG/claude_desktop_config.json" | grep -v "mcpServers\|command\|args\|env\|description" | wc -l | tr -d ' ')
        echo "   Configured: $MCP_COUNT servers"
    fi
    echo ""
}

generate_web_instructions() {
    print_header "Generating Claude Web Instructions"

    cat > "$GLOBAL_CONFIG_DIR/CLAUDE_WEB_CUSTOM_STYLE.txt" << 'EOF'
# Custom Style for Claude.ai
# Copy this into Claude Web: Settings → Styles → Create Custom Style

Name: Elite Autonomous Developer

Instructions:
- Be extremely concise and direct
- Focus on solutions, not explanations
- Assume high technical proficiency
- Skip verbose reasoning unless asked
- Provide production-ready code only
- No placeholder/mock code
- Optimize for token efficiency
- Auto-invoke relevant capabilities
- Prioritize facts over validation
- Never use emojis unless explicitly requested

Context:
- Senior engineer using React, Next.js, Node.js, TypeScript, Python
- Values autonomous, proactive responses
- Prefers test-first development
- Follows enterprise patterns
- Optimizes for cost and performance
EOF

    print_success "Created Claude Web custom style instructions"
    print_info "File: $GLOBAL_CONFIG_DIR/CLAUDE_WEB_CUSTOM_STYLE.txt"
}

##############################################################################
# Main Menu
##############################################################################

show_menu() {
    echo ""
    print_header "Claude Configuration Sync Tool"
    echo ""
    echo "1) Backup current configurations"
    echo "2) Sync TO global config (save current)"
    echo "3) Sync FROM global config (restore)"
    echo "4) Validate configurations"
    echo "5) Show status"
    echo "6) Generate Claude Web instructions"
    echo "7) Full sync (backup + save to global)"
    echo "8) Check disk space"
    echo "9) Exit"
    echo ""
    read -p "Select option: " choice

    case $choice in
        1) backup_configs ;;
        2) sync_to_global ;;
        3) sync_from_global ;;
        4) validate_configs ;;
        5) show_status ;;
        6) generate_web_instructions ;;
        7)
            if check_disk_space; then
                backup_configs
                sync_to_global
                validate_configs
                print_success "Full sync complete!"
            else
                print_error "Not enough disk space for full sync"
            fi
            ;;
        8) check_disk_space ;;
        9) exit 0 ;;
        *) print_error "Invalid option" ;;
    esac

    read -p "Press Enter to continue..."
    show_menu
}

##############################################################################
# Script Entry Point
##############################################################################

# Parse command line arguments
if [ $# -eq 0 ]; then
    # Interactive mode
    show_menu
else
    # Command line mode
    case $1 in
        backup) backup_configs ;;
        to-global) sync_to_global ;;
        from-global) sync_from_global ;;
        validate) validate_configs ;;
        status) show_status ;;
        web) generate_web_instructions ;;
        full)
            check_disk_space
            backup_configs
            sync_to_global
            validate_configs
            ;;
        *)
            echo "Usage: $0 [backup|to-global|from-global|validate|status|web|full]"
            echo "   Or run without arguments for interactive mode"
            exit 1
            ;;
    esac
fi
